export const GENERATED_SENTENCE_COUNT_PER_BATCH = 10
export const GENERATED_SENTENCE_COUNT_PER_KNOWLEDGE_POINT = 5
export const MAX_LOW_PRIORITY_VOCABULARIES = 10
export const MAX_LOW_PRIORITY_GRAMMAR = 5
