export const DESIRED_SENTENCE_COUNT_PER_BATCH = 20
export const DESIRED_SENTENCE_COUNT_PER_KNOWLEDGE_POINT = 5
export const MAX_LOW_PRIORITY_VOCABULARIES = 15
export const MAX_LOW_PRIORITY_GRAMMAR = 5
