export const DESIRED_SENTENCE_COUNT_PER_BATCH = 5
export const SENTENCE_URGENT_AMOUNT_THRESHOLD = 3
export const SENTENCE_HIGH_AMOUNT_THRESHOLD = 5
export const MAX_LOW_PRIORITY_VOCABULARIES = 15
export const MAX_LOW_PRIORITY_GRAMMAR = 5
export const DEFAULT_MAX_CONCURRENCY = 5
export const MAX_LLM_RETRY_TIMES = 3
